# Generated by Django 4.2.7 on 2023-11-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopMessage', models.CharField(max_length=50)),
                ('paragraph', models.CharField(max_length=100)),
            ],
        ),
    ]
