# Generated by Django 4.2.7 on 2023-11-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=50)),
                ('para1', models.CharField(max_length=200)),
                ('h3', models.CharField(max_length=50)),
                ('para2', models.CharField(max_length=250)),
                ('para3', models.CharField(max_length=300)),
            ],
        ),
    ]
