# Generated by Django 4.2.7 on 2023-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0004_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='para1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='h1',
            new_name='name',
        ),
    ]
