# Generated by Django 4.2.7 on 2023-11-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0005_teachers_rename_para1_student_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
