# Generated by Django 4.2.7 on 2023-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0006_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('duration', models.IntegerField(blank=True, default=3, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
