# Generated by Django 4.2.7 on 2023-11-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0007_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='h3',
            new_name='Age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='para2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='para3',
        ),
    ]
