# Generated by Django 4.2.7 on 2023-11-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0009_rename_age_student_age_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
