# Generated by Django 4.2.7 on 2023-11-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0011_rename_teachers_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
