# Generated by Django 4.2.7 on 2023-11-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0015_teacher_image_teacher_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
    ]
