# Generated by Django 4.2.7 on 2023-11-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joanApp', '0016_remove_courses_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
